[package]
name = "tinyworld"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
rand = "0.8.5"
rmp-serde = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }
uuid = { version = "1.10.0", features = ["v4"] }
